import 'models/recipe.dart';
import 'models/ingredient.dart';

class RecipeManager {
  List<Recipe> getRecipes() {
    return [
      Recipe(
        1,
        "Лосось в соусе терияки",
        "Нежное филе лосося, приготовленное в ароматном соусе терияки с нотками имбиря и чеснока.",
        [
          Ingredient(name: "Соевый соус", measurement: "8 ст. ложек"),
          Ingredient(name: "Вода", measurement: "6 ст. ложек"),
          Ingredient(name: "Мед", measurement: "3 ст. ложки"),
          Ingredient(name: "Коричневый сахар", measurement: "2 ст. ложки"),
          Ingredient(name: "Чеснок", measurement: "3 зубчика"),
          Ingredient(name: "Тертый свежий имбирь", measurement: "1 ст. ложка"),
          Ingredient(name: "Лимонный сок", measurement: "1.5 ст. ложки"),
          Ingredient(name: "Кукурузный крахмал", measurement: "1 ст. ложка"),
          Ingredient(name: "Растительное масло", measurement: "1 ч. ложка"),
          Ingredient(name: "Филе лосося", measurement: "680 г"),
          Ingredient(name: "Кунжут", measurement: "по вкусу"),
        ],
        45 * 60,
        "assets/Images/salmon_in_teriyaki_sauce.png",
      ),
      Recipe(
        2,
        "Бургер с двумя котлетами",
        "Сочный двойной бургер с хрустящими котлетами и свежими овощами.",
        [
          Ingredient(name: "Булочка для бургера", measurement: "1 шт."),
          Ingredient(name: "Говяжья котлета", measurement: "2 шт. (по 100 г)"),
          Ingredient(name: "Салат", measurement: "50 г"),
          Ingredient(name: "Помидор", measurement: "1 шт."),
          Ingredient(name: "Лук", measurement: "1/2 шт."),
          Ingredient(name: "Сыр чеддер", measurement: "2 ломтика"),
          Ingredient(name: "Кетчуп", measurement: "1 ст. ложка"),
          Ingredient(name: "Горчица", measurement: "1 ч. ложка"),
          Ingredient(name: "Масло для жарки", measurement: "1 ст. ложка"),
        ],
        60 * 60,
        "assets/Images/burger_with_two_cutlets.png",
      ),
      Recipe(
        3,
        "Стейк из говядины по-грузински с кукурузой",
        "Классический грузинский стейк с пряными специями и сливочным соусом.",
        [
          Ingredient(name: "Говядина", measurement: "400 г"),
          Ingredient(name: "Лук", measurement: "1 шт."),
          Ingredient(name: "Чеснок", measurement: "2 зубчика"),
          Ingredient(name: "Сливочное масло", measurement: "50 г"),
          Ingredient(name: "Сливки", measurement: "100 мл"),
          Ingredient(name: "Хмели-сунели", measurement: "1 ч. ложка"),
          Ingredient(name: "Соль", measurement: "по вкусу"),
          Ingredient(name: "Перец", measurement: "по вкусу"),
          Ingredient(name: "Масло для жарки", measurement: "2 ст. ложки"),
        ],
        75 * 60,
        "assets/Images/georgian_beef_steak.png",
      ),
      Recipe(
        4,
        "Пицца Маргарита домашняя",
        "Традиционная итальянская пицца с томатами, моцареллой и базиликом.",
        [
          Ingredient(name: "Тесто для пиццы", measurement: "200 г"),
          Ingredient(name: "Моцарелла", measurement: "150 г"),
          Ingredient(name: "Помидоры", measurement: "100 г"),
          Ingredient(name: "Базилик", measurement: "5-6 листьев"),
          Ingredient(name: "Оливковое масло", measurement: "1 ст. ложка"),
          Ingredient(name: "Соль", measurement: "щепотка"),
          Ingredient(name: "Томатный соус", measurement: "3 ст. ложки"),
        ],
        25 * 60,
        "assets/Images/homemade_pizza_margarita.png",
      ),
      Recipe(
        5,
        "Паста с морепродуктами",
        "Ароматная паста с креветками, мидиями и сливочным соусом.",
        [
          Ingredient(name: "Спагетти", measurement: "200 г"),
          Ingredient(name: "Креветки", measurement: "150 г"),
          Ingredient(name: "Мидии", measurement: "100 г"),
          Ingredient(name: "Сливки", measurement: "150 мл"),
          Ingredient(name: "Чеснок", measurement: "2 зубчика"),
          Ingredient(name: "Петрушка", measurement: "1 ст. ложка"),
          Ingredient(name: "Оливковое масло", measurement: "2 ст. ложки"),
          Ingredient(name: "Соль", measurement: "по вкусу"),
          Ingredient(name: "Перец", measurement: "по вкусу"),
        ],
        25 * 60,
        "assets/Images/pasta_with_seafood.png",
      ),
      Recipe(
        6,
        "Поке боул с сыром тофу",
        "Свежий гавайский салат с тунцом, авокадо и сырным акцентом.",
        [
          Ingredient(name: "Тунец", measurement: "200 г"),
          Ingredient(name: "Авокадо", measurement: "1 шт."),
          Ingredient(name: "Рис", measurement: "150 г"),
          Ingredient(name: "Соевый соус", measurement: "2 ст. ложки"),
          Ingredient(name: "Сыр фета", measurement: "50 г"),
          Ingredient(name: "Огурец", measurement: "1/2 шт."),
          Ingredient(name: "СеSAMe масло", measurement: "1 ч. ложка"),
          Ingredient(name: "Соль", measurement: "по вкусу"),
        ],
        30 * 60,
        "assets/Images/poke_bowl_with_cheese.png",
      ),
      Recipe(
        7,
        "Тосты с голубикой и бананом",
        "Сладкий и полезный тост с фруктами и мёдом.",
        [
          Ingredient(name: "Хлеб для тостов", measurement: "2 ломтика"),
          Ingredient(name: "Банан", measurement: "1 шт."),
          Ingredient(name: "Черника", measurement: "50 г"),
          Ingredient(name: "Мёд", measurement: "1 ст. ложка"),
          Ingredient(name: "Сливочное масло", measurement: "1 ч. ложка"),
          Ingredient(name: "Кокосовая стружка", measurement: "1 ч. ложка (по желанию)"),
        ],
        45 * 60,
        "assets/Images/toast_with_blueberries_and_banana.png",
      ),
    ];
  }
}